spring:
    application:
        name: dinory
    codec:
        max-in-memory-size: 16MB

    datasource:
        username: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect

    security:
        oauth2:
            client:
                registration:
                    google:
                        scope:
                            - email
                            - profile
                        redirect-uri: "{baseUrl}/oauth2/callback/google"

                    naver:
                        scope:
                            - name
                            - email
                        client-name: Naver
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/oauth2/callback/naver"

                    kakao:
                        scope:
                            - profile_nickname
                            # account_email은 비즈니스 앱만 사용 가능 (일반 앱은 수집 불가)
                        client-name: Kakao
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/oauth2/callback/kakao"
                        client-authentication-method: client_secret_post

                provider:
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response

                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

jwt:
    access-token-expire: 300000
    refresh-token-expire: 604800000

ai:
    server:
        url: http://localhost:8000

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: alpha
